services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluelock-frontend
    ports:
      - '8765:80'
    restart: always
    networks:
      - bluelock-net
networks:
  bluelock-net:
    driver: bridge
