services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: bluelock-frontend
    volumes:
      - ./.env.prod:/app/.env
    ports:
      - '8888:80'
    restart: always
