services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bluelock-frontend
    volumes:
      - ./.env:/app/.env
    ports:
      - '8765:80'
    restart: always
