name: Deploy Frontend & Docker Compose

on:
  push:
    branches:
      - main # ทริกเกอร์เมื่อมีการ Push ไปที่ main branch
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # บอก GitHub ให้ใช้ Self-Hosted Runner ของคุณ

    steps:
      - name: Checkout Frontend Code # Step นี้จะ Checkout โค้ดของ Frontend Repository ปัจจุบัน
        uses: actions/checkout@v4

      - name: Sync Frontend Code to Deployment Directory # คัดลอกโค้ด Frontend ที่ Checkout มา ไปยังโฟลเดอร์จริงบน Server
        run: |
          rsync -av --delete --exclude '.git/' "${GITHUB_WORKSPACE}/" "/home/BUU/65160309/bluelock/Fronend-Bluelock-007/"

      - name: Build and Deploy Docker Compose # รันคำสั่ง Docker Compose
        run: |
          cd /home/BUU/65160309/bluelock/Fronend-Bluelock-007/
          docker compose down --volumes
          docker compose build --no-cache
          docker compose up -d --force-recreate

      # - name: Clean up Runner Workspace (Optional but Recommended)
      #   run: |
      #     rm -rf "${GITHUB_WORKSPACE}"
